# any name we want
name: test github actions

# we define on which actions github must check our code
on:
  # if we push any changes on github when branch = master or develop_test
  push:
    branches: [ master, develop_test ]
  # we want also check any pull_reguest on these branches-ignore:
  pull_request:
    branches: [ master, develop_test ]

# now we define how we check our code, we must do a few jobs
jobs:
  # first TASK has name "build" and we define OS we usually run our project and steps to create environmental (python..)
  build:
    runs-on: ubuntu-latest
    steps:
      # first step - we take our repository and "move" it to check
      - uses: actions/checkout@v2
      # second step
      - name: Install python
        uses: actions/setup-python@v2
        # define version of python
        with:
          python-version: 3.7
      # third step
      - name: Install deps
        # because we want to run a few commands, we write "|" after the keyword
        # we need the latest pip (2 runs)
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt
      # fourth step - we need flake8 in current directory
      - name: Run flake8
        run: flake8 .
