name: test github actions

on:
  push:
    branches: [ master, develop_test ]
  pull_request:
    branches: [ master, develop_test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install flake8 and reguirements
        run: pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8 part 1
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Lint with flake8 part 2
        run: flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
